name = "commit-worker"
type = "webpack"
zone_id = "59551d4d25eb0b71d903be74d1288bf9"
usage_model = ""
compatibility_flags = []
routes = [
  "chrisdearman.xyz/api/commit",
]
compatibility_date = "2022-01-25"
