#!/usr/bin/env python3

import argparse
import sys
import os
import hashlib
import subprocess

URL = "https://storage.googleapis.com/chrisdearman.xyz/assets/"
ROOT = os.path.dirname(os.path.dirname(__file__))
ASSETS_PATH = os.path.join(ROOT, "assets")

def download_url(url, out_file):
  subprocess.check_call(["curl", "-L", "-#", "-o", out_file, url])

def sha256_file(path):
  with open(path, "br") as f:
    s = f.read()
  m = hashlib.sha256()
  m.update(s)
  return m.hexdigest()

def main():
  for name in os.listdir(ASSETS_PATH):
    if not name.endswith(".sha256"):
      continue
    path = os.path.join(ASSETS_PATH, name)
    with open(path) as f:
      sha256 = f.read().strip()
    file_name = name.removesuffix(".sha256") + "-" + sha256
    file_path = os.path.join(ASSETS_PATH, file_name)
    if os.path.isfile(file_path):
      actual_sha256 = sha256_file(file_path)
      if actual_sha256 != sha256:
        os.remove(file_path)
    if not os.path.isfile(file_path):
      download_path = file_path + ".tmp"
      url = URL + file_name
      download_url(url, download_path)
      actual_sha256 = sha256_file(download_path)
      if actual_sha256 != sha256:
        os.remove(download_path)
        print("SHA256 mismatch for {} expected {} was {}".format(
            download_path, sha256, actual_sha256))
        return 1
      os.rename(download_path, file_path)


if __name__ == '__main__':
  sys.exit(main())
