#!/usr/bin/env python3

import argparse
import sys

ASSETS = [
  ("advocate_c45_regular.woff", "5ed0f40f2b1e2ac5dc8c1aa735b450fc5f68c568afced2fb0ae13ccc46a66d1d"),
  ("equity_text_a_regular.woff", "32ca0c5f762eb6f60f65ad54d54ba176a9572df5556250bacd27e26748e0e6d0"),
]

def main():
  pass

if __name__ == '__main__':
  sys.exit(main())
